# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ILES_app", "0003_evaluation_comments_evaluation_date_evaluated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("supervisor", "Supervisor"),
                    ("admin", "Admin"),
                ],
                max_length=50,
            ),
        ),
    ]
