# Generated by Codex on 2026-04-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_supervisor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_students',
                to='ILES_app.supervisor',
            ),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='evaluation_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_logs',
                to='ILES_app.supervisor',
            ),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                ],
                default='pending',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='weekly_logs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
