# Generated by Django 6.0.5 on 2026-05-07 22:01

import ILES_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0011_customuser_unique_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', ILES_app.models.CustomUserManager()),
            ],
        ),
    ]
