# Generated by Django 6.0.5 on 2026-06-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0011_customuser_email_verified_at_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='place_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ILES_app.company'),
        ),
    ]
