# Generated by Django 6.0.5 on 2026-06-05 09:54

import django.db.models.deletion
from django.db import migrations, models


def migrate_supervisor_place_of_work(apps, schema_editor):
    Company = apps.get_model('ILES_app', 'Company')
    Supervisor = apps.get_model('ILES_app', 'Supervisor')
    for supervisor in Supervisor.objects.all():
        place_name = getattr(supervisor, 'place_of_work', None)
        if place_name:
            company, _ = Company.objects.get_or_create(name=place_name)
            supervisor.place_of_work_temp = company
            supervisor.save(update_fields=['place_of_work_temp'])


def reverse_migrate_supervisor_place_of_work(apps, schema_editor):
    Supervisor = apps.get_model('ILES_app', 'Supervisor')
    for supervisor in Supervisor.objects.all():
        company = getattr(supervisor, 'place_of_work', None)
        if company:
            supervisor.place_of_work_temp = company.name
            supervisor.save(update_fields=['place_of_work_temp'])


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='supervisor',
            name='place_of_work_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ILES_app.company'),
        ),
        migrations.RunPython(migrate_supervisor_place_of_work, reverse_migrate_supervisor_place_of_work),
        migrations.RemoveField(
            model_name='supervisor',
            name='place_of_work',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='place_of_work_temp',
            new_name='place_of_work',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='place_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ILES_app.company'),
        ),
    ]
