# Generated by Django 6.0.5 on 2026-06-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0013_evaluation_weekly_log'),
    ]

    operations = []
