# Generated by Django 6.0.5 on 2026-06-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0002_remove_student_placement_evaluation_weekly_log_and_more'),
        ('ILES_app', '0014_academicevaluation_academicevaluationdetail'),
    ]

    operations = [
    ]
